# -*- coding: utf-8 -*-
SECTIONS = [
{"key":"win","title":"Win Actions","pal":("#e9f6ea","#f2faf2","#74b97c","#2f7d3a"),"entries":[
 {"f":"1","en":"Self-Pick","cn":"自摸","ds":"You select your winning tile from the wall."},
 {"f":"2","kid":1,"en":"Win by Kong Replacement","cn":"槓上開花",
  "ds":"The winning tile is a replacement tile drawn after declaring a Kong (four of a kind).",
  "rep":"Replaces Self-Pick — score 2, not 2 + 1.",
  "ex":"Mixed Flush 3 + Dragon 1 + Kong Replacement 2 = 6 Fan",
  "h":"5s 5s 5s 5s | 2s 3s 4s | 6s 7s 8s | dg dg dg | 9s 9s*"},
 {"f":"9","kid":1,"en":"Double Kong Replacement","cn":"槓上槓",
  "ds":"Call a Kong, call a second Kong using the replacement tile, then win on the second replacement.",
  "rep":"Replaces Self-Pick and Win by Kong Replacement — score 9 only.",
  "ex":"Mixed Flush 3 + Dragon 1 + Double Kong 9 = 13 Fan (limit)",
  "h":"2p 2p 2p 2p | 7p 7p 7p 7p | 4p 5p 6p | dr dr dr | 9p 9p*"},
 {"f":"1","en":"Concealed Hand","cn":"門前清",
  "ds":"You did not take any tiles from other players in order to win.",
  "h":"xx xx xx xx xx xx xx xx xx xx xx xx xx | 4s*"},
 {"f":"1","en":"Robbing the Kong","cn":"搶槓",
  "ds":"You win by interrupting another player upgrading a Pong (a triplet) to a Kong using your winning tile.",
  "ex":"Mixed Flush 3 + Dragon 2 + Robbing the Kong 1 = 6 Fan \u2014 all four copies are in their Kong, so the robbed tile must complete a sequence",
  "h":"dg dg dg | dr dr dr | 2m 3m 4m | 6m 7m 8m* | 5m 5m"},
 {"f":"1","en":"Moon Under The Sea","cn":"海底撈月",
  "ds":"Your winning tile was the last tile in the wall or the last discard.",
}]},
{"key":"set","title":"Hands by Set Type","pal":("#fbeae4","#fdf3ef","#dc9179","#b1482c"),"entries":[
 {"f":"1","en":"All Sequences","cn":"平糊","ds":"All four sets are sequences, plus a pair, which may be honours.",
  "ex":"All Sequences 1 = 1 Fan \u2014 on its own this sits below a 3 Fan table minimum",
  "h":"2m 3m 4m | 5m 6m 7m | 3p 4p 5p | 6p 7p 8p | we we"},
 {"f":"3","en":"All Triplets","cn":"對對糊","ds":"All four sets are three of a kind, plus a pair.",
  "ex":"All Triplets 3 = 3 Fan, or 4 Fan if 東 is your seat or the round wind",
  "h":"1m 1m 1m | 5p 5p 5p | 8s 8s 8s | we we we | 3m 3m"},
 {"f":"8","kid":1,"en":"All Concealed Triplets","cn":"四暗刻",
  "ds":"All sets are triplets and no tiles taken from other players. Win by self-pick, or by taking a discard that completes the pair. Claiming a discard to finish a triplet would expose that set — you still win, but with only three concealed triplets the hand downgrades to All Triplets 3.",
  "rep":"Replaces All Triplets — score 8, not 8 + 3.",
  "ex":"All Concealed Triplets 8 = 8 Fan, or 9 if 北 is your seat or the round wind \u2014 All Triplets 3 is replaced, and concealment is required, so Concealed Hand is built in",
  "h":"2p 2p 2p | 6p 6p 6p | 4s 4s 4s | wn wn wn | 9m 9m*"},
 {"f":"13","kid":1,"en":"All Quadruplets","cn":"四槓子","ds":"All four sets are quadruplets, plus a pair. Kongs may be claimed from discards. A discard that completes your fourth Kong is not a win \u2014 declare the Kong, draw a Replacement Tile, and win on that, or on a later discard once all four Kongs are down and only the pair is open.",
  "rep":"Replaces All Triplets.",
  "ex":"All Quadruplets 13 = 13 Fan \u2014 the limit; the 中 Kong and All Triplets are not added",
  "h":"2m 2m 2m 2m | 5p 5p 5p 5p | 9s 9s 9s 9s | dr dr dr dr | 7m 7m"}]},
{"key":"tile","title":"Hands by Tile Type","pal":("#e4f0fb","#f0f7fd","#79b0de","#1c5f9e"),"entries":[
 {"f":"1x","en":"Dragon","cn":"三元牌",
  "ds":"A triplet of dragon tiles. Any one of the three below scores on its own, and each one you hold scores again.",
  "opts":[("dr dr dr","Red 1 Fan"),("dg dg dg","Green 1 Fan"),("dw dw dw","White 1 Fan")],
  "ex":"One triplet = 1 Fan. Two = 2 Fan. All three is Big Three Dragons 8, which replaces this.",
  "h":"dr dr dr | dg dg dg | dw dw dw"},
 {"f":"5","kid":1,"en":"Small Three Dragons","cn":"小三元",
  "ds":"Two dragon triplets and a pair of the third dragon.",
  "rep":"Replaces the per-triplet Dragon score — score 5 flat.",
  "ex":"Small Three Dragons 5 + Mixed Flush 3 = 8 Fan \u2014 the per-triplet Dragon score is replaced, not added",
  "h":"dr dr dr | dg dg dg | dw dw | 2p 3p 4p | 6p 7p 8p"},
 {"f":"8","kid":1,"en":"Big Three Dragons","cn":"大三元","ds":"Three dragon triplets.",
  "rep":"Replaces Dragon and Small Three Dragons — score 8 flat.",
  "ex":"Big Three Dragons 8 = 8 Fan \u2014 Dragon and Small Three Dragons are replaced; two suits here, so no Mixed Flush",
  "h":"dr dr dr | dg dg dg | dw dw dw | 3p 4p 5p | 6m 6m"},
 {"f":"1x","en":"Round Wind / Seat Wind","cn":"圈風 / 門風",
  "ds":"A game runs four rounds \u2014 East, South, West, North. A triplet of the current round's wind, or of your own seat wind, scores. Each of the four below counts <b>only</b> if it is one of those two for you.",
  "opts":[("we we we","East 1 Fan"),("ws ws ws","South 1 Fan"),("ww ww ww","West 1 Fan"),("wn wn wn","North 1 Fan")],
  "ex":"A triplet of the other two winds scores nothing. One triplet that is both the round wind and your seat wind = 2 Fan.",
  "h":"we we we | ws ws ws | ww ww ww | wn wn wn"},
 {"f":"6","kid":1,"en":"Small Four Winds","cn":"小四喜",
  "ds":"Three wind triplets and a pair of the fourth wind.",
  "rep":"Replaces Round / Seat Wind — score 6 flat.",
  "ex":"Small Four Winds 6 + Mixed Flush 3 = 9 Fan \u2014 the Round / Seat Wind score is replaced, not added",
  "h":"we we we | ws ws ws | ww ww ww | wn wn | 4s 5s 6s"},
 {"f":"13","kid":1,"en":"Big Four Winds","cn":"大四喜","ds":"Four wind triplets.",
  "rep":"Replaces Round / Seat Wind and Small Four Winds.",
  "ex":"Big Four Winds 13 = 13 Fan \u2014 the limit; All Triplets 3 and Mixed Flush 3 are not counted on top",
  "h":"we we we | ws ws ws | ww ww ww | wn wn wn | 5p 5p"},
 {"f":"3","en":"Mixed Flush","cn":"混一色","ds":"Your hand contains only one suit plus honours (winds & dragons). Can have both pongs and chows (sequences).",
  "ex":"Mixed Flush 3 + Dragon 1 = 4 Fan \u2014 the 東 pair scores nothing, only a triplet would",
  "h":"1m 2m 3m | 4m 5m 6m | 7m 8m 9m | dr dr dr | we we"},
 {"f":"7","kid":1,"en":"Full Flush","cn":"清一色","ds":"Your hand contains only one suit. Can have both pongs and chows (sequences).",
  "rep":"Replaces Mixed Flush — score 7, not 7 + 3.",
  "ex":"Full Flush 7 = 7 Fan \u2014 Mixed Flush 3 is replaced, not added",
  "h":"1s 1s 1s | 2s 3s 4s | 4s 5s 6s | 7s 8s 9s | 9s 9s"},
 {"f":"4","en":"Mixed Terminals","cn":"混么九",
  "ds":"Your hand contains only ones, nines and honours (winds & dragons). 3 Fan from All Triplets is included.",
  "ex":"Mixed Terminals 4 + Dragon 1 = 5 Fan \u2014 the All Triplets 3 is already inside the 4",
  "h":"1m 1m 1m | 9p 9p 9p | 1s 1s 1s | dr dr dr | we we"},
 {"f":"13","kid":1,"en":"All Terminals","cn":"清么九",
  "ds":"Your hand contains only ones and nines. 3 Fan from All Triplets is included.",
  "rep":"Replaces Mixed Terminals and All Triplets.",
  "ex":"All Terminals 13 = 13 Fan \u2014 the limit; Mixed Terminals 4 and All Triplets 3 are replaced, not added",
  "h":"1m 1m 1m | 9m 9m 9m | 1p 1p 1p | 9s 9s 9s | 1s 1s"},
 {"f":"10","kid":1,"en":"All Honours","cn":"字一色",
  "ds":"Your hand contains only honour tiles (winds & dragons). 3 Fan from All Triplets is already included.",
  "rep":"Replaces Mixed Terminals and All Triplets. No suit tiles, so Mixed Flush does not apply.",
  "ex":"All Honours 10 + Small Three Dragons 5 = 15, capped at the 13 Fan limit \u2014 中中中 發發發 白白 is Small Three Dragons",
  "h":"we we we | ws ws ws | dr dr dr | dg dg dg | dw dw"},
 {"f":"1x","en":"Kong","cn":"槓",
  "ds":"Each quadruplet scores. A concealed Kong is worth more, since no one helped you build it.",
  "var":True,
  "opts":[("5s 5s 5s 5s","open \u2014 1 Fan each"),
          ("xx 5s 5s xx","concealed \u2014 2 Fan each")],
  "ex":"A concealed Kong shows its outer tiles face down. Four Kongs is All Quadruplets 13, which replaces this",
  "h":"5s 5s 5s 5s"}]},
{"key":"spec","title":"Special Hands","pal":("#f8f4de","#fcfaee","#cbb955","#7e6c17"),"entries":[
 {"f":"4","en":"Seven Pairs","cn":"七對子",
  "ds":"Seven different pairs. Can stack with Mixed Flush, Full Flush and All Honours.",
  "var":True,
  "ex":"* Seven Pairs 4 = 4 Fan alone.  ** + Mixed Flush 3 = 7 Fan, or + Full Flush 7 = 11.  *** + All Honours 10 = 14, capped at the 13 Fan limit. You can never Pong or Chow here, so Concealed Hand is built in",
  "opts":[("2m 2m | 5m 5m | 8m 8m | 3p 3p | 7p 7p | 4s 4s | dr dr","three suits \u2014 4 Fan  *"),
          ("2m 2m | 5m 5m | 7m 7m | 9m 9m | we we | ws ws | dr dr","with Mixed Flush \u2014 7 Fan  **"),
          ("we we | ws ws | ww ww | wn wn | dr dr | dg dg | dw dw","with All Honours \u2014 13 limit  ***")],
  "h":"2m 2m | 5m 5m | 8m 8m | 3p 3p | 7p 7p | 4s 4s | dr dr"},
 {"f":"2x","en":"Luxury Seven Pairs","cn":"豪華七對",
  "ds":"A Seven Pairs hand in which four identical tiles stand as two of the seven pairs. Scores for each such set.",
  "var":True,
  "ex":"Seven Pairs 4 + Luxury 2 = 6 Fan. A Kong breaks it. Dragon Fan needs a triplet, so an honour quad adds nothing; Concealed Hand is built in",
  "h":"dr dr dr dr | 5m 5m | 8m 8m | 3p 3p | 7p 7p | 4s 4s*"},
 {"f":"5","en":"Knitted Tiles","cn":"組合龍",
  "ds":"Special run made in this sequence: 1-4-7 in one suit, 2-5-8 in the second, 3-6-9 in the third \u2014 nine tiles \"knitted\" across the suits. Plus one ordinary set and a pair.",
  "var":True,
  "ex":"Knitted Tiles 5 = 5 Fan \u2014 three suits, so no flush, and 中中 scores nothing. The non-knitted set may be Ponged or Chowed; Concealed adds 1",
  "h":"1m 4m 7m | 2p 5p 8p | 3s 6s 9s | | | 4s 5s 6s | dr dr*"},
 {"f":"8","en":"Lesser Honours","cn":"全不靠",
  "ds":"Fourteen single tiles, no set and no pair. A mix of honour tiles (winds & dragons) and knitted runs (1-4-7, 2-5-8, 3-6-9), one to each suit. There are only two shapes: 9 knitted + 5 honours, or 8 knitted + 6 honours.",
  "var":True,
  "ex":"Lesser Honours 8 = 8 Fan. With no sets there is nothing to claim, so Concealed Hand is built in. Self-Pick and flowers still do.",
  "opts":[("1m 4m 7m | 2p 5p 8p | 3s 6s 9s | | | we ws ww wn dw*","all 9 knitted  +  any 5 honours"),
          ("1s 4s 7s | 2m 5m 8m | 6p 9p | | | we ws ww wn dr dg*","any 8 knitted  +  any 6 honours")],
  "h":"1m 4m 7m | 2p 5p 8p | 3s 6s 9s | | | we ws ww wn dw*"},
 {"f":"10","en":"Greater Honours","cn":"七星不靠",
  "ds":"Must have all seven honours (winds & dragons) as singles plus <b>any</b> seven knitted tiles \u2014 fourteen singles, no set and no pair.",
  "var":True,
  "ex":"Greater Honours 10 = 10 Fan. Concealed by definition, so Concealed Hand is built in. Self-Pick and flowers still do.",
  "h":"1m 4m 7m | 2p 5p 8p | 3s | | | we ws ww wn dr dg dw*"},
 {"f":"13","en":"Thirteen Orphans","cn":"十三么",
  "ds":"One of each 1 and 9 from all three suits, and one of each of the seven honours (winds & dragons), plus one extra duplicate of any tile in the hand. Concealed by definition.",
  "ex":"Thirteen Orphans 13 = 13 Fan \u2014 the limit, so nothing adds on top",
  "h":"1m 9m | 1p 9p | 1s 9s | we ws ww wn | dr dg dw | 1m*"},
 {"f":"13","en":"Nine Gates","cn":"九蓮寶燈",
  "ds":"111 2345678 999 of a single suit. The winning tile can be any 1 to 9 of that suit — nine ways to win, hence the name. Must be fully concealed.",
  "ex":"Nine Gates 13 = 13 Fan \u2014 the limit; the Full Flush 7 inside it is not added",
  "h":"1s 1s 1s | 2s 3s 4s 5s 6s 7s 8s | 9s 9s 9s | 5s*"},
 {"f":"13","en":"Blessing of Heaven","cn":"天糊","ds":"As dealer, your beginning hand wins.",
  "ex":"Blessing of Heaven 13 = 13 Fan \u2014 the pattern needs no Fan of its own, so even a chicken hand wins",
  "h":"1p 2p 3p | 4p 5p 6p | 7p 8p 9p | dg dg dg | we we*"},
 {"f":"13","en":"Blessing of Earth","cn":"地糊","ds":"As non-dealer, you win using the dealer's first discard.",
  "ex":"Blessing of Earth 13 = 13 Fan \u2014 the pattern needs no Fan of its own, so even a chicken hand wins",
  "h":"2s 3s 4s | 5s 6s 7s | 3m 4m 5m | 6m 7m 8m | dw dw*"},
 {"f":"13","en":"Blessing of Man","cn":"人糊","ds":"As non-dealer, you win on your first turn with a self-pick.",
  "ex":"Blessing of Man 13 = 13 Fan \u2014 the pattern needs no Fan of its own, so even a chicken hand wins",
  "h":"1m 2m 3m | 4p 5p 6p | 7s 8s 9s | 2p 3p 4p | 8m 8m*"}
]},
{"key":"flw","title":"Bonus Tiles (Flowers & Seasons)","pal":("#fbe6f0","#fdf1f7","#dd8ab5","#a3306d"),"entries":[
 {"f":"1","en":"No Flowers or Seasons","cn":"無花",
  "ds":"You drew none of the eight bonus tiles all hand. Nothing to show \u2014 the Fan is for their absence.",
  "h":""},
 {"f":"1x","en":"Seat Flower or Season","cn":"正花",
  "ds":"1 Fan for each flower or season matching your seat number. East is 1, South 2, West 3, North 4.",
  "h":""},
 {"f":"2","en":"All Flowers or All Seasons","cn":"一檯花",
  "ds":"You have all four flowers, <b>or</b> all four seasons. A mix of four bonus tiles taken from both groups does not count.","h":""},
 {"f":"3","en":"Seven Flowers","cn":"花糊",
  "ds":"Collect seven of the eight bonus tiles (flowers and seasons) and you may win at once, no matter what your hand holds.",
  "h":""},
 {"f":"8","en":"Eight Flowers","cn":"大花糊",
  "ds":"Collect all eight bonus tiles and you may win at once, no matter what your hand holds.",
  "h":""}]}
]

HOWTO = [
 "Your hand's Fan score is the SUM of the Fan of all matching features.",
 "Indented features REPLACE the parent feature — count the child only, never both.",
 "Unless stated otherwise, triplets and quadruplets are interchangeable.",
 "A red triangle marks the winning tile. Calculate payout on the Payment Table.",
 "\u2020 marks hands whose rules vary by table \u2014 MCR or Taiwanese imports. Agree them before the first deal.",
]
PAYROWS = [(0,1,7,48),(1,2,8,64),(2,4,9,96),(3,8,10,128),(4,16,11,192),(5,24,12,256),(6,32,"13+",384)]
TERMS = [("Mahjong","麻雀 ma zoek"),("Chow","上 soeng"),("Pong","碰 pung"),("Kong","槓 gong"),
         ("Win from Self Pick","自摸 zi mo"),("Win from Discard","食糊 sik wu"),
         ("Chicken (0 Fan) Hand","雞和 gaai wu")]
SUITROWS = [("Dots","筒子 tung zi","1p 2p 3p 4p 5p 6p 7p 8p 9p"),
            ("Sticks","索子 sok zi","1s 2s 3s 4s 5s 6s 7s 8s 9s"),
            ("Man","萬子 maan zi","1m 2m 3m 4m 5m 6m 7m 8m 9m"),
            ("Winds","風 fung","we ws ww wn"),
            ("Dragons","三元 saam jyun","dr dg dw"),
            ("Flowers","花 faa","h5 h6 h7 h8"),
            ("Seasons","季 gwai","h1 h2 h3 h4")]
TERMINOLOGY = [
 "A winning hand is four sets (melds) and a pair. Sets are a sequence, a triplet, or a quadruplet.",
 "Sequences are three tiles of one suit in order (1-2-3 up to 7-8-9). Complete one from the player on your left by calling Chow.",
 "Triplets are three identical tiles, completed from any player's discard as a Pong.",
 "Quadruplets are four identical tiles, completed as a Kong. A self-formed quadruplet is a Concealed Kong. When declaring any Kong, draw a Replacement Tile from the dead end of the wall.",
 "Hong Kong style usually plays with a Minimum Fan, commonly 3. Below it you cannot declare a win.",
 "Scoring is also capped at a Limit, commonly 13 Fan. A hand worth more than the Limit simply pays the Limit.",
]
PAYNOTES = [
 "This table uses \"discarder pays all\" (全銃制), which increases the penalty for discarding another player's winning tile.",
 "Self pick: all three players pay the points for your Fan total.",
 "Discard: only the discarder pays, at 2x the points.",
 "Older tables share that cost instead \u2014 the discarder pays double and the other two pay single each, for the same total.",
 "With chips, paying the Fan count (5 Fan = 5 chips) is quicker but flattens rewards: a limit hand pays 13, not 384.",
]

# --- reference chart: numbered suits on the left, named honours/bonus on the right ---
NUM_ROWS = [("Dots",   "筒子 tung zi", "p"),
            ("Sticks", "索子 sok zi",  "s"),
            ("Man",    "萬子 maan zi", "m")]

HONOUR_ROWS = [
 ("Winds",   "風 fung",
  [("we","East"), ("ws","South"), ("ww","West"), ("wn","North")]),
 ("Dragons", "三元 saam jyun",
  [("dr","Hung Zung"), ("dg","Faat Coi"), ("dw","Baak Baan")]),
 ("Flowers", "花 faa",
  [("h5","Plum"), ("h6","Orchid"), ("h7","Mum"), ("h8","Bamboo")]),
 ("Seasons", "季 gwai",
  [("h1","Spring"), ("h2","Summer"), ("h3","Autumn"), ("h4","Winter")]),
]
